codex:
    model: codellama_Q
    codellama_tokenizer_name: 'codellama/CodeLlama-7b-hf' 
    prompt: ./prompts/api_no_video.prompt
load_models:
    codellama_Q: True
    llm_query: True
    llm_guess: True

# BEGIRATU PARAMETROEN ESPEZIFIKAZIOAK -> (Temperature, batch_size, ...)