codex:
    model: codellama_Q
    model_name: 'codellama/CodeLlama-7b-hf' 
    prompt: ./prompts/api_no_video.prompt
cognition:
    model: codellama_Q
    is_setted: True
load_models:
    codellama_Q: True