dataset:
  data_path: ./data/refcoco
  dataset_name: RefCOCO
  split_by: unc  # [google, unc]
  split: testA
  version: refcoco
  batch_size: 1 # set to number 3 
  max_samples: 4

codex:
  prompt: ./prompts/benchmarks/refcoco.prompt
fixed_code_file: ./prompts/fixed_code/glip.prompt

load_models:
  gpt3_general: False

save: True
save_codex: False
use_cached_codex: False

results_dir: ./results/refcoco/all/
execute_code: True

ratio_box_area_to_image_area: 0.03
crop_larger_margin: False

