dataset:
    data_path: ./data/okvqa
    dataset_name: OKVQA
    split: test
    testing: False
    max_samples: 
    batch_size: 12 # to test set 1f
    start_sample: 0
codex:
    prompt: ./prompts/benchmarks/okvqa.prompt

results_dir: ./results/okvqa/all/

load_models:
    maskrcnn: False
    clip: False
    glip: False
    owlvit: False
    tcl: False
    gpt3_list: False # Ez dakit noiz erabiltzen den
    gpt3_qa: False
    gpt3_guess: False
    depth: False
    blip: True
    saliency: False
    xvlm: False

fixed_code_file: ./prompts/fixed_code/blip2.prompt
save: True